version: '3'

services:
  zip_money_backend:
    build: ./zip_money_backend
    restart: always
    ports:
      - "8000:8000"
    entrypoint: python ./app/manage.py runserver 0.0.0.0:8000
    env_file:
      - ./zip_money_backend/.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zip_money_db
      - POSTGRES_HOST=zip_money_db
      - POSTGRES_PORT=5432
    volumes:
      - type: bind
        source: ./zip_money_backend
        target: /app
    depends_on:
      - zip_money_db

  zip_money_frontend:
    build: ./zip_money_frontend
    restart: always
    env_file:
      - ./zip_money_frontend/.env
    entrypoint: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./zip_money_frontend/
        target: /app
    depends_on:
      - zip_money_backend

  zip_money_db:
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zip_money_db
    ports:
      - '1238:5432'
    volumes:
      - type: bind
        source: ./zip_money_db/
        target: /var/lib/postgresql/data/

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"