[tool.flake8]
ignore = "E203"
exclude = ".venv"
max-line-length = 79

[tool.black]
line-length = 79
fmt = false

[tool.isort]
profile = "black"
line_length = 79
skip_gitignore = true
multi_line_output = 3

[tool.pytest.ini_options]
env = [
    "DB_NAME=testdb",
    "DB_PORT=1238",
]
