# Generated by Django 4.2.6 on 2023-11-22 20:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="budget",
            old_name="remaining_budget",
            new_name="budget",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="total_budget",
        ),
    ]
