# Generated by Django 4.2.6 on 2023-11-22 21:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0002_rename_remaining_budget_budget_budget_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BudgetTransaction",
        ),
    ]
