# Generated by Django 5.0 on 2023-12-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0004_alter_budget_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="budget",
            field=models.FloatField(default=0),
        ),
    ]
