# Generated by Django 5.0 on 2023-12-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0005_alter_budget_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="budget",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
