# Generated by Django 5.0 on 2023-12-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0006_alter_budget_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetassigneduser",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
