# Generated by Django 5.0 on 2023-12-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0003_transaction_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
