# Generated by Django 5.0 on 2024-01-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0005_remove_category_image_category_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="symbol",
            field=models.CharField(max_length=2),
        ),
    ]
